### ISSUE TITLE
More than just eth1 ?

### ISSUE THREAD

**Issue by modonovan** [rare-freertr/freeRtr-containerlab#3]
Is the freeRTR container capable of having more than one endpoint? Would like to add a few more devices to the topology but can't seem to add endpoints with anything other than eth1 as the interface.

**Comment by modonovan** [comment]
Nevermind, this is working perfectly for eth >1 now. It must have been a transient issue with my local system at the time I tried it earlier. Working well with a 4 node deployment (square topology). Great work on getting this working!

**Comment by frederic-loui** [comment]
> Nevermind, this is working perfectly for eth >1 now. It must have been a transient issue with my local system at the time I tried it earlier. Working well with a 4 node deployment (square topology). Great work on getting this working!

You can now also play with some new labs [here](https://github.com/rare-freertr/freeRtr-containerlab/tree/main/lab) @modonovan. There is a lab that might be of your interest: `rift with CLOS architecture`

**Comment by modonovan** [comment]
Excellent stuff Frederic, many thanks and hope all is well with you!

**Comment by mc36** [comment]
remove all regex first from the repo until i unfollowed frederic to the hell.....
