### ISSUE TITLE
`clab-topo` topic

### ISSUE THREAD

**Issue by hellt** [rare-freertr/freeRtr-containerlab#7]
Hi,
we now track clab labs with the `clab-topo` topic https://github.com/topics/clab-topo
you may want to add it to the repos that feature the clab topology file for others to discover it

**Comment by frederic-loui** [comment]
Thanks for the heads up !
I'll have look ASAP ...

Thanks
Frederic

Le jeu. 18 avr. 2024 à 15:39, Roman Dodin ***@***.***> a
écrit :

**Comment by frederic-loui** [comment]
`clab-topo`  topic added ! Thanks !
